name: midmate
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  android_intent_plus: ^6.0.0
  cupertino_icons: ^1.0.8
  fl_chart: ^1.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_local_notifications: ^19.1.0
  flutter_localization: ^0.3.2
  flutter_native_splash: ^2.4.5
  flutter_slidable: ^4.0.0
  flutter_svg: ^2.0.17
  get_it: ^8.0.3
  intl: ^0.20.2
  lottie: ^3.3.1
  path_provider: ^2.1.5
  jbh_ringtone: 
  shared_preferences: ^2.5.2
  sqflite: ^2.4.2
  timezone: ^0.10.0
  uuid: ^4.5.1
  workmanager: ^0.9.0+3

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  sqflite_common_ffi: ^2.3.6
  test: ^1.26.2

flutter:
  generate: true
  uses-material-design: true

  # flutter_intl:
  #   enabled: true
  #   template_arbs_file: lib/l10n/app_en.arb  # Make sure this file exists
  #   output_dir: lib/l10n/generated
  assets:
    - assets/icons/
    - assets/icons/med_types/
    - assets/images/
    - assets/icons/med_types/drop.png
    
    

flutter_native_splash:
  color: "#000000" # Background color
  android_12:
    color: "#000000"
flutter_intl:
  enabled: true
